/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import controladores.ControladorPrincipal;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author franco
 */
public class vistaBatalla extends javax.swing.JFrame {

    /**
     * Creates new form vistaBatalla
     */
    public vistaBatalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton225 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jButton204 = new javax.swing.JButton();
        jButton205 = new javax.swing.JButton();
        jButton206 = new javax.swing.JButton();
        jButton207 = new javax.swing.JButton();
        jButton208 = new javax.swing.JButton();
        jButton209 = new javax.swing.JButton();
        jButton210 = new javax.swing.JButton();
        jButton211 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();
        jButton213 = new javax.swing.JButton();
        jButton214 = new javax.swing.JButton();
        jButton215 = new javax.swing.JButton();
        jButton216 = new javax.swing.JButton();
        jButton217 = new javax.swing.JButton();
        jButton218 = new javax.swing.JButton();
        jButton219 = new javax.swing.JButton();
        jButton220 = new javax.swing.JButton();
        jButton221 = new javax.swing.JButton();
        jButton222 = new javax.swing.JButton();
        jButton223 = new javax.swing.JButton();
        jButton224 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton231 = new javax.swing.JButton();
        jButton232 = new javax.swing.JButton();
        jButton233 = new javax.swing.JButton();
        jButton234 = new javax.swing.JButton();
        jButton235 = new javax.swing.JButton();
        imagenD1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imagenD2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tirarD1 = new javax.swing.JButton();
        tirarD2 = new javax.swing.JButton();
        imagenD3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagenD4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tirarD3 = new javax.swing.JButton();
        tirarD4 = new javax.swing.JButton();
        resultD2 = new javax.swing.JTextField();
        resultD3 = new javax.swing.JTextField();
        resultD4 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        resultD1 = new javax.swing.JTextField();
        contMov = new javax.swing.JLabel();
        contAtk = new javax.swing.JLabel();
        contInv = new javax.swing.JLabel();
        contTram = new javax.swing.JLabel();
        contMag = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(15, 15));

        jButton1.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jPanel1.add(jButton225);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jPanel1.add(jButton5);
        jPanel1.add(jButton6);
        jPanel1.add(jButton7);
        jPanel1.add(jButton8);
        jPanel1.add(jButton9);
        jPanel1.add(jButton10);
        jPanel1.add(jButton11);
        jPanel1.add(jButton12);
        jPanel1.add(jButton13);
        jPanel1.add(jButton14);
        jPanel1.add(jButton15);
        jPanel1.add(jButton16);
        jPanel1.add(jButton17);
        jPanel1.add(jButton18);
        jPanel1.add(jButton19);
        jPanel1.add(jButton20);
        jPanel1.add(jButton21);
        jPanel1.add(jButton22);
        jPanel1.add(jButton23);
        jPanel1.add(jButton24);
        jPanel1.add(jButton25);
        jPanel1.add(jButton26);
        jPanel1.add(jButton27);
        jPanel1.add(jButton28);
        jPanel1.add(jButton29);

        jButton30.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel1.add(jButton30);
        jPanel1.add(jButton31);
        jPanel1.add(jButton32);
        jPanel1.add(jButton33);
        jPanel1.add(jButton34);
        jPanel1.add(jButton35);
        jPanel1.add(jButton36);
        jPanel1.add(jButton37);
        jPanel1.add(jButton38);
        jPanel1.add(jButton39);
        jPanel1.add(jButton40);
        jPanel1.add(jButton41);
        jPanel1.add(jButton42);
        jPanel1.add(jButton43);
        jPanel1.add(jButton44);

        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45);
        jPanel1.add(jButton46);
        jPanel1.add(jButton47);
        jPanel1.add(jButton48);
        jPanel1.add(jButton49);
        jPanel1.add(jButton50);
        jPanel1.add(jButton51);
        jPanel1.add(jButton52);
        jPanel1.add(jButton53);

        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton54);
        jPanel1.add(jButton55);
        jPanel1.add(jButton56);
        jPanel1.add(jButton57);
        jPanel1.add(jButton58);
        jPanel1.add(jButton59);
        jPanel1.add(jButton60);
        jPanel1.add(jButton61);
        jPanel1.add(jButton62);
        jPanel1.add(jButton63);
        jPanel1.add(jButton64);

        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton65);
        jPanel1.add(jButton66);
        jPanel1.add(jButton67);
        jPanel1.add(jButton68);
        jPanel1.add(jButton69);
        jPanel1.add(jButton70);
        jPanel1.add(jButton71);
        jPanel1.add(jButton72);
        jPanel1.add(jButton73);
        jPanel1.add(jButton74);
        jPanel1.add(jButton75);
        jPanel1.add(jButton76);
        jPanel1.add(jButton77);
        jPanel1.add(jButton78);
        jPanel1.add(jButton79);
        jPanel1.add(jButton80);
        jPanel1.add(jButton81);
        jPanel1.add(jButton82);
        jPanel1.add(jButton83);
        jPanel1.add(jButton84);
        jPanel1.add(jButton85);
        jPanel1.add(jButton86);
        jPanel1.add(jButton87);
        jPanel1.add(jButton88);
        jPanel1.add(jButton89);
        jPanel1.add(jButton90);
        jPanel1.add(jButton91);

        jButton92.setText("jButton92");
        jPanel1.add(jButton92);

        jButton93.setText("jButton93");
        jPanel1.add(jButton93);

        jButton94.setText("jButton94");
        jPanel1.add(jButton94);

        jButton95.setText("jButton95");
        jPanel1.add(jButton95);

        jButton96.setText("jButton96");
        jPanel1.add(jButton96);

        jButton97.setText("jButton97");
        jPanel1.add(jButton97);

        jButton98.setText("jButton98");
        jPanel1.add(jButton98);

        jButton99.setText("jButton99");
        jPanel1.add(jButton99);

        jButton100.setText("jButton100");
        jPanel1.add(jButton100);

        jButton101.setText("jButton101");
        jPanel1.add(jButton101);

        jButton102.setText("jButton102");
        jPanel1.add(jButton102);

        jButton103.setText("jButton103");
        jPanel1.add(jButton103);

        jButton104.setText("jButton104");
        jPanel1.add(jButton104);
        jPanel1.add(jButton105);

        jButton106.setText("jButton106");
        jPanel1.add(jButton106);

        jButton107.setText("jButton107");
        jPanel1.add(jButton107);

        jButton108.setText("jButton108");
        jPanel1.add(jButton108);

        jButton109.setText("jButton109");
        jPanel1.add(jButton109);

        jButton110.setText("jButton110");
        jPanel1.add(jButton110);

        jButton111.setText("jButton111");
        jPanel1.add(jButton111);

        jButton112.setText("jButton112");
        jPanel1.add(jButton112);

        jButton113.setText("jButton113");
        jPanel1.add(jButton113);

        jButton114.setText("jButton114");
        jPanel1.add(jButton114);

        jButton115.setText("jButton115");
        jPanel1.add(jButton115);

        jButton116.setText("jButton116");
        jPanel1.add(jButton116);

        jButton117.setText("jButton117");
        jPanel1.add(jButton117);

        jButton118.setText("jButton118");
        jPanel1.add(jButton118);

        jButton119.setText("jButton119");
        jPanel1.add(jButton119);
        jPanel1.add(jButton120);

        jButton121.setText("jButton121");
        jPanel1.add(jButton121);

        jButton122.setText("jButton122");
        jPanel1.add(jButton122);

        jButton123.setText("jButton123");
        jPanel1.add(jButton123);

        jButton124.setText("jButton124");
        jPanel1.add(jButton124);

        jButton125.setText("jButton125");
        jPanel1.add(jButton125);

        jButton126.setText("jButton126");
        jPanel1.add(jButton126);

        jButton127.setText("jButton127");
        jPanel1.add(jButton127);

        jButton128.setText("jButton128");
        jPanel1.add(jButton128);

        jButton129.setText("jButton129");
        jPanel1.add(jButton129);

        jButton130.setText("jButton130");
        jPanel1.add(jButton130);

        jButton131.setText("jButton131");
        jPanel1.add(jButton131);

        jButton132.setText("jButton132");
        jPanel1.add(jButton132);

        jButton133.setText("jButton133");
        jPanel1.add(jButton133);

        jButton134.setText("jButton134");
        jPanel1.add(jButton134);
        jPanel1.add(jButton135);

        jButton136.setText("jButton136");
        jPanel1.add(jButton136);

        jButton137.setText("jButton137");
        jPanel1.add(jButton137);

        jButton138.setText("jButton138");
        jPanel1.add(jButton138);

        jButton139.setText("jButton139");
        jPanel1.add(jButton139);

        jButton140.setText("jButton140");
        jPanel1.add(jButton140);

        jButton141.setText("jButton141");
        jPanel1.add(jButton141);

        jButton142.setText("jButton142");
        jPanel1.add(jButton142);

        jButton143.setText("jButton143");
        jPanel1.add(jButton143);

        jButton144.setText("jButton144");
        jPanel1.add(jButton144);

        jButton145.setText("jButton145");
        jButton145.setPreferredSize(new java.awt.Dimension(85, 80));
        jPanel1.add(jButton145);

        jButton146.setText("jButton146");
        jPanel1.add(jButton146);

        jButton147.setText("jButton147");
        jPanel1.add(jButton147);

        jButton148.setText("jButton148");
        jPanel1.add(jButton148);

        jButton149.setText("jButton149");
        jPanel1.add(jButton149);
        jPanel1.add(jButton150);

        jButton151.setText("jButton151");
        jPanel1.add(jButton151);

        jButton152.setText("jButton152");
        jPanel1.add(jButton152);

        jButton153.setText("jButton153");
        jPanel1.add(jButton153);

        jButton154.setText("jButton154");
        jPanel1.add(jButton154);

        jButton155.setText("jButton155");
        jPanel1.add(jButton155);

        jButton156.setText("jButton156");
        jPanel1.add(jButton156);

        jButton157.setText("jButton157");
        jPanel1.add(jButton157);

        jButton158.setText("jButton158");
        jPanel1.add(jButton158);

        jButton159.setText("jButton159");
        jPanel1.add(jButton159);

        jButton160.setText("jButton160");
        jPanel1.add(jButton160);

        jButton161.setText("jButton161");
        jPanel1.add(jButton161);

        jButton162.setText("jButton162");
        jPanel1.add(jButton162);

        jButton163.setText("jButton163");
        jPanel1.add(jButton163);

        jButton164.setText("jButton164");
        jPanel1.add(jButton164);

        jButton165.setText("jButton165");
        jPanel1.add(jButton165);

        jButton166.setText("jButton166");
        jPanel1.add(jButton166);

        jButton167.setText("jButton167");
        jPanel1.add(jButton167);

        jButton168.setText("jButton168");
        jPanel1.add(jButton168);

        jButton169.setText("jButton169");
        jPanel1.add(jButton169);

        jButton170.setText("jButton170");
        jPanel1.add(jButton170);

        jButton171.setText("jButton171");
        jPanel1.add(jButton171);

        jButton172.setText("jButton172");
        jPanel1.add(jButton172);

        jButton173.setText("jButton173");
        jPanel1.add(jButton173);

        jButton174.setText("jButton174");
        jPanel1.add(jButton174);

        jButton175.setText("jButton175");
        jPanel1.add(jButton175);

        jButton176.setText("jButton176");
        jPanel1.add(jButton176);

        jButton177.setText("jButton177");
        jPanel1.add(jButton177);

        jButton178.setText("jButton178");
        jPanel1.add(jButton178);

        jButton179.setText("jButton179");
        jPanel1.add(jButton179);

        jButton180.setText("jButton180");
        jPanel1.add(jButton180);

        jButton181.setText("jButton181");
        jPanel1.add(jButton181);

        jButton182.setText("jButton182");
        jPanel1.add(jButton182);

        jButton183.setText("jButton183");
        jPanel1.add(jButton183);

        jButton184.setText("jButton184");
        jPanel1.add(jButton184);

        jButton185.setText("jButton185");
        jPanel1.add(jButton185);

        jButton186.setText("jButton186");
        jPanel1.add(jButton186);

        jButton187.setText("jButton187");
        jPanel1.add(jButton187);

        jButton188.setText("jButton188");
        jPanel1.add(jButton188);

        jButton189.setText("jButton189");
        jPanel1.add(jButton189);

        jButton190.setText("jButton190");
        jPanel1.add(jButton190);

        jButton191.setText("jButton191");
        jPanel1.add(jButton191);

        jButton192.setText("jButton192");
        jPanel1.add(jButton192);

        jButton193.setText("jButton193");
        jPanel1.add(jButton193);

        jButton194.setText("jButton194");
        jPanel1.add(jButton194);

        jButton195.setText("jButton195");
        jPanel1.add(jButton195);

        jButton196.setText("jButton196");
        jPanel1.add(jButton196);

        jButton197.setText("jButton197");
        jPanel1.add(jButton197);

        jButton198.setText("jButton198");
        jPanel1.add(jButton198);

        jButton199.setText("jButton199");
        jPanel1.add(jButton199);

        jButton200.setText("jButton200");
        jPanel1.add(jButton200);

        jButton201.setText("jButton201");
        jPanel1.add(jButton201);

        jButton202.setText("jButton202");
        jPanel1.add(jButton202);

        jButton203.setText("jButton203");
        jPanel1.add(jButton203);

        jButton204.setText("jButton204");
        jPanel1.add(jButton204);

        jButton205.setText("jButton205");
        jPanel1.add(jButton205);

        jButton206.setText("jButton206");
        jPanel1.add(jButton206);

        jButton207.setText("jButton207");
        jPanel1.add(jButton207);

        jButton208.setText("jButton208");
        jPanel1.add(jButton208);

        jButton209.setText("jButton209");
        jPanel1.add(jButton209);

        jButton210.setText("jButton210");
        jPanel1.add(jButton210);

        jButton211.setText("jButton211");
        jPanel1.add(jButton211);

        jButton212.setText("jButton212");
        jPanel1.add(jButton212);

        jButton213.setText("jButton213");
        jPanel1.add(jButton213);

        jButton214.setText("jButton214");
        jPanel1.add(jButton214);

        jButton215.setText("jButton215");
        jPanel1.add(jButton215);

        jButton216.setText("jButton216");
        jPanel1.add(jButton216);

        jButton217.setText("jButton217");
        jPanel1.add(jButton217);

        jButton218.setText("jButton218");
        jPanel1.add(jButton218);

        jButton219.setText("jButton219");
        jPanel1.add(jButton219);

        jButton220.setText("jButton220");
        jPanel1.add(jButton220);

        jButton221.setText("jButton221");
        jPanel1.add(jButton221);

        jButton222.setText("jButton222");
        jPanel1.add(jButton222);

        jButton223.setText("jButton223");
        jPanel1.add(jButton223);

        jButton224.setText("jButton224");
        jPanel1.add(jButton224);

        jButton231.setText("Mover");

        jButton232.setText("Atacar");

        jButton233.setText("Invocar");
        jButton233.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton233ActionPerformed(evt);
            }
        });

        jButton234.setText("Trampa");

        jButton235.setText("Magia");

        imagenD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dado7.png"))); // NOI18N

        jLabel2.setText("Resultado Dado 1");

        imagenD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dado7.png"))); // NOI18N

        jLabel4.setText("Resultado Dado 2");

        tirarD1.setText("Tirar Dado 1");

        tirarD2.setText("Tirar Dado 2");

        imagenD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dado7.png"))); // NOI18N
        imagenD3.setText("jLabel5");

        jLabel6.setText("Resultado Dado 3");

        imagenD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dado7.png"))); // NOI18N
        imagenD4.setText("jLabel7");

        jLabel8.setText("Resultado Dado 4");

        tirarD3.setText("Tirar Dado 3");

        tirarD4.setText("Tirar Dado 4");

        resultD2.setEditable(false);

        resultD3.setEditable(false);

        resultD4.setEditable(false);

        jLabel9.setText("imagenJ1");

        jLabel10.setText("imagenJ2");

        jLabel11.setText("imagenJ3");

        jLabel12.setText("imagenJ4");

        jLabel13.setText("Jefe 1");

        jLabel14.setText("Jefe 2");

        jLabel15.setText("Jefe 3");

        jLabel16.setText("Jefe 4");

        resultD1.setEditable(false);

        contMov.setText("0");

        contAtk.setText("0");

        contInv.setText("0");

        contTram.setText("0");

        contMag.setText("0");

        jLabel19.setText("Guardados:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel17.setText("Acciones:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton233, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contInv))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton232, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contAtk))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton234, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton235, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(contMag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(contTram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(37, 37, 37))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton231, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contMov, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenD3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tirarD1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenD1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tirarD3))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultD3)
                            .addComponent(resultD1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultD4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tirarD2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultD2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imagenD2))
                        .addComponent(tirarD4))
                    .addComponent(imagenD4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel13))
                    .addComponent(jLabel17))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton231)
                            .addComponent(contMov))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton232)
                            .addComponent(contAtk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton233)
                            .addComponent(contInv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton234)
                            .addComponent(contTram))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton235)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(contMag)
                                .addGap(4, 4, 4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imagenD1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenD2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(resultD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(resultD1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tirarD1)
                            .addComponent(tirarD2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imagenD3)
                            .addComponent(imagenD4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(resultD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(resultD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tirarD3)
                            .addComponent(tirarD4))))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton233ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton233ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton233ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton65ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contAtk;
    private javax.swing.JLabel contInv;
    private javax.swing.JLabel contMag;
    private javax.swing.JLabel contMov;
    private javax.swing.JLabel contTram;
    private javax.swing.JLabel imagenD1;
    private javax.swing.JLabel imagenD2;
    private javax.swing.JLabel imagenD3;
    private javax.swing.JLabel imagenD4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton204;
    private javax.swing.JButton jButton205;
    private javax.swing.JButton jButton206;
    private javax.swing.JButton jButton207;
    private javax.swing.JButton jButton208;
    private javax.swing.JButton jButton209;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton210;
    private javax.swing.JButton jButton211;
    private javax.swing.JButton jButton212;
    private javax.swing.JButton jButton213;
    private javax.swing.JButton jButton214;
    private javax.swing.JButton jButton215;
    private javax.swing.JButton jButton216;
    private javax.swing.JButton jButton217;
    private javax.swing.JButton jButton218;
    private javax.swing.JButton jButton219;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton220;
    private javax.swing.JButton jButton221;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton223;
    private javax.swing.JButton jButton224;
    private javax.swing.JButton jButton225;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton231;
    private javax.swing.JButton jButton232;
    private javax.swing.JButton jButton233;
    private javax.swing.JButton jButton234;
    private javax.swing.JButton jButton235;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField resultD1;
    private javax.swing.JTextField resultD2;
    private javax.swing.JTextField resultD3;
    private javax.swing.JTextField resultD4;
    private javax.swing.JButton tirarD1;
    private javax.swing.JButton tirarD2;
    private javax.swing.JButton tirarD3;
    private javax.swing.JButton tirarD4;
    // End of variables declaration//GEN-END:variables
    
    
    //Tablero:
    //Gets del tablero
    public JButton getBotonTablero1(){
        return this.jButton1;
    }
    public JButton getBotonTablero2(){
        return this.jButton2;
    }
    public JButton getBotonTablero3(){
        return this.jButton3;
    }
    public JButton getBotonTablero4(){
        return this.jButton4;
    }
    public JButton getBotonTablero5(){
        return this.jButton5;
    }
    public JButton getBotonTablero6(){
        return this.jButton6;
    }
    public JButton getBotonTablero7(){
        return this.jButton7;
    }
    public JButton getBotonTablero8(){
        return this.jButton8;
    }
    public JButton getBotonTablero9(){
        return this.jButton9;
    }
    public JButton getBotonTablero10(){
        return this.jButton10;
    }
    public JButton getBotonTablero11(){
        return this.jButton11;
    }
    public JButton getBotonTablero12(){
        return this.jButton12;
    }
    public JButton getBotonTablero13(){
        return this.jButton13;
    }
    public JButton getBotonTablero14(){
        return this.jButton14;
    }
    public JButton getBotonTablero15(){
        return this.jButton15;
    }
    public JButton getBotonTablero16(){
        return this.jButton16;
    }
    public JButton getBotonTablero17(){
        return this.jButton17;
    }
    public JButton getBotonTablero18(){
        return this.jButton18;
    }
    public JButton getBotonTablero19(){
        return this.jButton19;
    }
    public JButton getBotonTablero20(){
        return this.jButton20;
    }
    public JButton getBotonTablero21(){
        return this.jButton21;
    }
    public JButton getBotonTablero22(){
        return this.jButton22;
    }
    public JButton getBotonTablero23(){
        return this.jButton23;
    }
    public JButton getBotonTablero24(){
        return this.jButton24;
    }
    public JButton getBotonTablero25(){
        return this.jButton25;
    }
    public JButton getBotonTablero26(){
        return this.jButton26;
    }
    public JButton getBotonTablero27(){
        return this.jButton27;
    }
    public JButton getBotonTablero28(){
        return this.jButton28;
    }
    public JButton getBotonTablero29(){
        return this.jButton29;
    }
    public JButton getBotonTablero30(){
        return this.jButton30;
    }
    public JButton getBotonTablero31(){
        return this.jButton31;
    }
    public JButton getBotonTablero32(){
        return this.jButton32;
    }
    public JButton getBotonTablero33(){
        return this.jButton33;
    }
    public JButton getBotonTablero34(){
        return this.jButton34;
    }
    public JButton getBotonTablero35(){
        return this.jButton35;
    }
    public JButton getBotonTablero36(){
        return this.jButton36;
    }
    public JButton getBotonTablero37(){
        return this.jButton37;
    }
    public JButton getBotonTablero38(){
        return this.jButton38;
    }
    public JButton getBotonTablero39(){
        return this.jButton39;
    }
    public JButton getBotonTablero40(){
        return this.jButton40;
    }
    public JButton getBotonTablero41(){
        return this.jButton41;
    }
    public JButton getBotonTablero42(){
        return this.jButton42;
    }
    public JButton getBotonTablero43(){
        return this.jButton43;
    }
    public JButton getBotonTablero44(){
        return this.jButton44;
    }
    public JButton getBotonTablero45(){
        return this.jButton45;
    }
    public JButton getBotonTablero46(){
        return this.jButton46;
    }
    public JButton getBotonTablero47(){
        return this.jButton47;
    }
    public JButton getBotonTablero48(){
        return this.jButton48;
    }
    public JButton getBotonTablero49(){
        return this.jButton49;
    }
    public JButton getBotonTablero50(){
        return this.jButton50;
    }
    public JButton getBotonTablero51(){
        return this.jButton51;
    }
    public JButton getBotonTablero52(){
        return this.jButton52;
    }
    public JButton getBotonTablero53(){
        return this.jButton53;
    }
    public JButton getBotonTablero54(){
        return this.jButton54;
    }
    public JButton getBotonTablero55(){
        return this.jButton55;
    }
    public JButton getBotonTablero56(){
        return this.jButton56;
    }
    public JButton getBotonTablero57(){
        return this.jButton57;
    }
    public JButton getBotonTablero58(){
        return this.jButton58;
    }
    public JButton getBotonTablero59(){
        return this.jButton59;
    }
    public JButton getBotonTablero60(){
        return this.jButton60;
    }
    public JButton getBotonTablero61(){
        return this.jButton61;
    }
    public JButton getBotonTablero62(){
        return this.jButton62;
    }
    public JButton getBotonTablero63(){
        return this.jButton63;
    }
    public JButton getBotonTablero64(){
        return this.jButton64;
    }
    public JButton getBotonTablero65(){
        return this.jButton65;
    }
    public JButton getBotonTablero66(){
        return this.jButton66;
    }
    public JButton getBotonTablero67(){
        return this.jButton67;
    }
    public JButton getBotonTablero68(){
        return this.jButton68;
    }
    public JButton getBotonTablero69(){
        return this.jButton69;
    }
    public JButton getBotonTablero70(){
        return this.jButton70;
    }
    public JButton getBotonTablero71(){
        return this.jButton71;
    }
    public JButton getBotonTablero72(){
        return this.jButton72;
    }
    public JButton getBotonTablero73(){
        return this.jButton73;
    }
    public JButton getBotonTablero74(){
        return this.jButton74;
    }
    public JButton getBotonTablero75(){
        return this.jButton75;
    }
    public JButton getBotonTablero76(){
        return this.jButton76;
    }
    public JButton getBotonTablero77(){
        return this.jButton77;
    }
    public JButton getBotonTablero78(){
        return this.jButton78;
    }
    public JButton getBotonTablero79(){
        return this.jButton79;
    }
    public JButton getBotonTablero80(){
        return this.jButton80;
    }
    public JButton getBotonTablero81(){
        return this.jButton81;
    }
    public JButton getBotonTablero82(){
        return this.jButton82;
    }
    public JButton getBotonTablero83(){
        return this.jButton83;
    }
    public JButton getBotonTablero84(){
        return this.jButton84;
    }
    public JButton getBotonTablero85(){
        return this.jButton85;
    }
    public JButton getBotonTablero86(){
        return this.jButton86;
    }
    public JButton getBotonTablero87(){
        return this.jButton87;
    }
    public JButton getBotonTablero88(){
        return this.jButton88;
    }
    public JButton getBotonTablero89(){
        return this.jButton89;
    }
    public JButton getBotonTablero90(){
        return this.jButton90;
    }
    public JButton getBotonTablero91(){
        return this.jButton91;
    }
    public JButton getBotonTablero92(){
        return this.jButton92;
    }
    public JButton getBotonTablero93(){
        return this.jButton93;
    }
    public JButton getBotonTablero94(){
        return this.jButton94;
    }
    public JButton getBotonTablero95(){
        return this.jButton95;
    }
    public JButton getBotonTablero96(){
        return this.jButton96;
    }
    public JButton getBotonTablero97(){
        return this.jButton97;
    }
    public JButton getBotonTablero98(){
        return this.jButton98;
    }
    public JButton getBotonTablero99(){
        return this.jButton99;
    }
    public JButton getBotonTablero100(){
        return this.jButton100;
    }
    public JButton getBotonTablero101(){
        return this.jButton101;
    }
    public JButton getBotonTablero102(){
        return this.jButton102;
    }
    public JButton getBotonTablero103(){
        return this.jButton103;
    }
    public JButton getBotonTablero104(){
        return this.jButton104;
    }
    public JButton getBotonTablero105(){
        return this.jButton105;
    }
    public JButton getBotonTablero106(){
        return this.jButton106;
    }
    public JButton getBotonTablero107(){
        return this.jButton107;
    }
    public JButton getBotonTablero108(){
        return this.jButton108;
    }
    public JButton getBotonTablero109(){
        return this.jButton109;
    }
    public JButton getBotonTablero110(){
        return this.jButton110;
    }
    public JButton getBotonTablero111(){
        return this.jButton111;
    }
    public JButton getBotonTablero112(){
        return this.jButton112;
    }
    public JButton getBotonTablero113(){
        return this.jButton113;
    }
    public JButton getBotonTablero114(){
        return this.jButton114;
    }
    public JButton getBotonTablero115(){
        return this.jButton115;
    }
    public JButton getBotonTablero116(){
        return this.jButton116;
    }
    public JButton getBotonTablero117(){
        return this.jButton117;
    }
    public JButton getBotonTablero118(){
        return this.jButton118;
    }
    public JButton getBotonTablero119(){
        return this.jButton119;
    }
    public JButton getBotonTablero120(){
        return this.jButton120;
    }
    public JButton getBotonTablero121(){
        return this.jButton121;
    }
    public JButton getBotonTablero122(){
        return this.jButton122;
    }
    public JButton getBotonTablero123(){
        return this.jButton123;
    }
    public JButton getBotonTablero124(){
        return this.jButton124;
    }
    public JButton getBotonTablero125(){
        return this.jButton125;
    }
    public JButton getBotonTablero126(){
        return this.jButton126;
    }
    public JButton getBotonTablero127(){
        return this.jButton127;
    }
    public JButton getBotonTablero128(){
        return this.jButton128;
    }
    public JButton getBotonTablero129(){
        return this.jButton129;
    }
    public JButton getBotonTablero130(){
        return this.jButton130;
    }
    public JButton getBotonTablero131(){
        return this.jButton131;
    }
    public JButton getBotonTablero132(){
        return this.jButton132;
    }
    public JButton getBotonTablero133(){
        return this.jButton133;
    }
    public JButton getBotonTablero134(){
        return this.jButton134;
    }
    public JButton getBotonTablero135(){
        return this.jButton135;
    }
    public JButton getBotonTablero136(){
        return this.jButton136;
    }
    public JButton getBotonTablero137(){
        return this.jButton137;
    }
    public JButton getBotonTablero138(){
        return this.jButton138;
    }
    public JButton getBotonTablero139(){
        return this.jButton139;
    }
    public JButton getBotonTablero140(){
        return this.jButton140;
    }
    public JButton getBotonTablero141(){
        return this.jButton141;
    }
    public JButton getBotonTablero142(){
        return this.jButton142;
    }
    public JButton getBotonTablero143(){
        return this.jButton143;
    }
    public JButton getBotonTablero144(){
        return this.jButton144;
    }
    public JButton getBotonTablero145(){
        return this.jButton145;
    }
    public JButton getBotonTablero146(){
        return this.jButton146;
    }
    public JButton getBotonTablero147(){
        return this.jButton147;
    }
    public JButton getBotonTablero148(){
        return this.jButton148;
    }
    public JButton getBotonTablero149(){
        return this.jButton149;
    }
    public JButton getBotonTablero150(){
        return this.jButton150;
    }
    public JButton getBotonTablero151(){
        return this.jButton151;
    }
    public JButton getBotonTablero152(){
        return this.jButton152;
    }
    public JButton getBotonTablero153(){
        return this.jButton153;
    }
    public JButton getBotonTablero154(){
        return this.jButton154;
    }
    public JButton getBotonTablero155(){
        return this.jButton155;
    }
    public JButton getBotonTablero156(){
        return this.jButton156;
    }
    public JButton getBotonTablero157(){
        return this.jButton157;
    }
    public JButton getBotonTablero158(){
        return this.jButton158;
    }
    public JButton getBotonTablero159(){
        return this.jButton159;
    }
    public JButton getBotonTablero160(){
        return this.jButton160;
    }
    public JButton getBotonTablero161(){
        return this.jButton161;
    }
    public JButton getBotonTablero162(){
        return this.jButton162;
    }
    public JButton getBotonTablero163(){
        return this.jButton163;
    }
    public JButton getBotonTablero164(){
        return this.jButton164;
    }
    public JButton getBotonTablero165(){
        return this.jButton165;
    }
    public JButton getBotonTablero166(){
        return this.jButton166;
    }
    public JButton getBotonTablero167(){
        return this.jButton167;
    }
    public JButton getBotonTablero168(){
        return this.jButton168;
    }
    public JButton getBotonTablero169(){
        return this.jButton169;
    }
    public JButton getBotonTablero170(){
        return this.jButton170;
    }
    public JButton getBotonTablero171(){
        return this.jButton171;
    }
    public JButton getBotonTablero172(){
        return this.jButton172;
    }
    public JButton getBotonTablero173(){
        return this.jButton173;
    }
    public JButton getBotonTablero174(){
        return this.jButton174;
    }
    public JButton getBotonTablero175(){
        return this.jButton175;
    }
    public JButton getBotonTablero176(){
        return this.jButton176;
    }
    public JButton getBotonTablero177(){
        return this.jButton177;
    }
    public JButton getBotonTablero178(){
        return this.jButton178;
    }
    public JButton getBotonTablero179(){
        return this.jButton179;
    }
    public JButton getBotonTablero180(){
        return this.jButton180;
    }
    public JButton getBotonTablero181(){
        return this.jButton181;
    }
    public JButton getBotonTablero182(){
        return this.jButton182;
    }
    public JButton getBotonTablero183(){
        return this.jButton183;
    }
    public JButton getBotonTablero184(){
        return this.jButton184;
    }
    public JButton getBotonTablero185(){
        return this.jButton185;
    }
    public JButton getBotonTablero186(){
        return this.jButton186;
    }
    public JButton getBotonTablero187(){
        return this.jButton187;
    }
    public JButton getBotonTablero188(){
        return this.jButton188;
    }
    public JButton getBotonTablero189(){
        return this.jButton189;
    }
    public JButton getBotonTablero190(){
        return this.jButton190;
    }
    public JButton getBotonTablero191(){
        return this.jButton191;
    }
    public JButton getBotonTablero192(){
        return this.jButton192;
    }
    public JButton getBotonTablero193(){
        return this.jButton193;
    }
    public JButton getBotonTablero194(){
        return this.jButton194;
    }
    public JButton getBotonTablero195(){
        return this.jButton195;
    }
    public JButton getBotonTablero196(){
        return this.jButton196;
    }
    public JButton getBotonTablero197(){
        return this.jButton197;
    }
    public JButton getBotonTablero198(){
        return this.jButton198;
    }
    public JButton getBotonTablero199(){
        return this.jButton199;
    }
    public JButton getBotonTablero200(){
        return this.jButton200;
    }
    public JButton getBotonTablero201(){
        return this.jButton201;
    }
    public JButton getBotonTablero202(){
        return this.jButton202;
    }
    public JButton getBotonTablero203(){
        return this.jButton203;
    }
    public JButton getBotonTablero204(){
        return this.jButton204;
    }
    public JButton getBotonTablero205(){
        return this.jButton205;
    }
    public JButton getBotonTablero206(){
        return this.jButton206;
    }
    public JButton getBotonTablero207(){
        return this.jButton207;
    }
    public JButton getBotonTablero208(){
        return this.jButton208;
    }
    public JButton getBotonTablero209(){
        return this.jButton209;
    }
    public JButton getBotonTablero210(){
        return this.jButton210;
    }
    public JButton getBotonTablero211(){
        return this.jButton211;
    }
    public JButton getBotonTablero212(){
        return this.jButton212;
    }
    public JButton getBotonTablero213(){
        return this.jButton213;
    }
    public JButton getBotonTablero214(){
        return this.jButton214;
    }
    public JButton getBotonTablero215(){
        return this.jButton215;
    }
    public JButton getBotonTablero216(){
        return this.jButton216;
    }
    public JButton getBotonTablero217(){
        return this.jButton217;
    }
    public JButton getBotonTablero218(){
        return this.jButton218;
    }
    public JButton getBotonTablero219(){
        return this.jButton219;
    }
    public JButton getBotonTablero220(){
        return this.jButton220;
    }
    public JButton getBotonTablero221(){
        return this.jButton221;
    }
    public JButton getBotonTablero222(){
        return this.jButton222;
    }
    public JButton getBotonTablero223(){
        return this.jButton223;
    }
    public JButton getBotonTablero224(){
        return this.jButton224;
    }
    public JButton getBotonTablero225(){
        return this.jButton225;
    }
    /////////////////////////////////////////
    
    public JButton getBoton1(){
        return this.tirarD1;
    }
    public JButton getBoton2(){
        return this.tirarD2;
    }
    public JButton getBoton3(){
        return this.tirarD3;
    }
    public JButton getBoton4(){
        return this.tirarD4;
    }
    //get imagenes dados.
    public JLabel getImagen1(){
        return this.imagenD1;
    }
    public JLabel getImagen2(){
        return this.imagenD2;
    }
    public JLabel getImagen3(){
        return this.imagenD3;
    }
    public JLabel getImagen4(){
        return this.imagenD4;
    }
    //get contadores.
    public JLabel getCantMov(){
        return this.contMov;
    }
    public JLabel getCantAtk(){
        return this.contAtk;
    }
    public JLabel getCatnInv(){
        return this.contInv;
    }
    public JLabel getCantTram(){
        return this.contTram;
    }
    public JLabel getCantMag(){
        return this.contMag;
    }
    //set para cambiar los contadores.
    public void setCantMov(int num){
        this.contMov.setText(Integer.toString(num));
    }
    public void setCantAtk(int num){
        this.contAtk.setText(Integer.toString(num));
    }
    public void setCantInv(int num){
        this.contInv.setText(Integer.toString(num));
    }
    public void setCantTram(int num){
        this.contTram.setText(Integer.toString(num));
    }
    public void setCantMag(int num){
        this.contMag.setText(Integer.toHexString(num));
    }
    //set para cambiar las imagenes.
    
    public void setImagen(ImageIcon imagen){
        this.imagenD1.setIcon(new ImageIcon("Imagenes\\carasDados\\3.png"));
        //this.imagenD1.setIcon(imagen);
    }
    //set para mostrar el resultado como texto.
    public void setResultadoD1(String nombre){
        this.resultD1.setText(nombre);
    }
    public void setResultadoD2(String nombre){
        this.resultD2.setText(nombre);
    }
    public void setResultadoD3(String nombre){
        this.resultD3.setText(nombre);
    }
    public void setResultadoD4(String nombre){
        this.resultD4.setText(nombre);
    }
         
    public void agregarListener(ActionListener al){
        this.tirarD1.addActionListener(al);
        this.tirarD2.addActionListener(al);
        this.tirarD3.addActionListener(al);
        this.tirarD4.addActionListener(al);
    }
}
